version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.2.14'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
    volumes:
      - './db:/bitnami'
  matomo:
    image: 'jameswang10/matomo_geoip:1.0'
    environment:
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './matomo:/bitnami'
